export const EmailDb = [
    {id: '1', name: 'Dalila Ouldcott', email: 'douldcottj@yellowpages.com', subject: 'wellish laminable ineunt popshop catalyte prismatize campimetrical lentisk excluding portlet coccinellid impestation Bangash Lollardist perameloid procerebrum presume cashmerette washbasin nainsook Odontolcae Alea holcodont welte', description: 'User-friendly value-added application 😊', avatar: 'https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-4/static/media/1.6a7d13c0.png', date: 'May 10, 2022'},
    {id: '2', name: 'Ardis Balderson', email: 'abaldersong@utexas.edu', subject: 'wellish laminable ineunt popshop catalyte prismatize campimetrical lentisk excluding portlet coccinellid impestation', avatar: 'https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-4/static/media/avatar-s-9.e2785e7a.jpg', description:'Focused impactful open system 📷 😃', date: 'May 10, 2022'},
    {id: '3', name: 'Modestine Spat', email: 'mspata@sina.com.cn', subject: 'wellish laminable ineunt popshop catalyte prismatize campimetrical lentisk excluding portlet coccinellid impestation', avatar: 'https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-4/static/media/9.8617df44.png', description:'Profound systemic alliance 🎉 🎊', date: 'May 10, 2022'},
    {id: '4', name: 'Eb Begg', email: 'ebegg9@wikia.com', subject: 'wellish laminable ineunt popshop catalyte prismatize campimetrical lentisk excluding portlet coccinellid impestation', avatar: 'https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-4/static/media/avatar-s-9.e2785e7a.jpg', description:'Organized value-added model', date: 'May 10, 2022'},
    {id: '5', name: 'Waldemar Mannering', email: 'wmannering3@mozilla.org', subject: 'wellish laminable ineunt popshop catalyte prismatize campimetrical lentisk excluding portlet coccinellid impestation', avatar: 'https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-4/static/media/11.9d340e5c.png', description:'Quality-focused methodical flexibility', date: 'May 10, 2022'},
    {id: '6', name: 'Louetta Esses', email: 'louettae@mail.com', subject: 'wellish laminable ineunt popshop catalyte prismatize campimetrical lentisk excluding portlet coccinellid impestation', avatar: 'https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-4/static/media/4.4bfb7963.png', description:'Waterfall Model Update', date: 'May 10, 2022'},
    {id: '7', name: 'Tressa Gass', email: 'tressag@mail.com', subject: 'wellish laminable ineunt popshop catalyte prismatize campimetrical lentisk excluding portlet coccinellid impestation', avatar: 'https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-4/static/media/2.c8691d67.png', description:'Company Report', date: 'May 10, 2022'},
    {id: '8', name: 'Tommy Sicilia', email: 'tommys@mail.com', subject: 'wellish laminable ineunt popshop catalyte prismatize campimetrical lentisk excluding portlet coccinellid impestation', avatar: 'https://pixinvent.com/demo/vuexy-react-admin-dashboard-template/demo-4/static/media/1.6a7d13c0.png', description:'Theme Update', date: 'May 10, 2022'},
]